name: Hotfix

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      base_commit_sha:
        required: true
        type: string
      branch_name:
        required: true
        type: string

jobs:
  hotfix:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_commit_sha }}

      - name: Create new branch
        run: |
          git switch -c hotfix-bases/${{ github.event.inputs.branch_name }}
          git push origin hotfix-bases/${{ github.event.inputs.branch_name }}
