name: Infra

on:
  workflow_call:
    inputs:
      open_infra_pr:
        required: true
        type: string
    secrets:
      GITOPS_DEMO_BOT_GITHUB_TOKEN:
        required: true

jobs:
  infra:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Infra PR
        if: inputs.open_infra_pr == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITOPS_DEMO_BOT_GITHUB_TOKEN }}
        run: |
          echo "Open PR Infra"
          TAG=$GITHUB_SHA bash scripts/open_infra_pr.sh
